axis_linear:
  x: 0
  y: 1
  z: 2
scale_linear:
  x: -0.1
  y: 0.1
  z: 0.2
axis_angular:
  yaw: 3
scale_angular:
  yaw: 0.5
  
enable_button: 0  # R2 shoulder button
enable_turbo_button: -1  # R1 shoulder button
